# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/yeek/kdedev/output/host/usr/bin/cmake

# The command to remove a file.
RM = /home/yeek/kdedev/output/host/usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /home/yeek/kdedev/output/host/usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yeek/kdedev/output/build/kdelibs-v4.7.1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build

# Include any dependencies generated for this target.
include kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/depend.make

# Include the progress variables for this target.
include kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/progress.make

# Include the compile flags for this target's objects.
include kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/flags.make

kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/kconfig_compiler_automoc.o: kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/flags.make
kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/kconfig_compiler_automoc.o: kdecore/kconfig_compiler/kconfig_compiler_automoc.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/CMakeFiles $(CMAKE_PROGRESS_1)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/kconfig_compiler_automoc.o"
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdecore/kconfig_compiler && g++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/kconfig_compiler.dir/kconfig_compiler_automoc.o -c /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdecore/kconfig_compiler/kconfig_compiler_automoc.cpp

kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/kconfig_compiler_automoc.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/kconfig_compiler.dir/kconfig_compiler_automoc.i"
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdecore/kconfig_compiler && g++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdecore/kconfig_compiler/kconfig_compiler_automoc.cpp > CMakeFiles/kconfig_compiler.dir/kconfig_compiler_automoc.i

kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/kconfig_compiler_automoc.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/kconfig_compiler.dir/kconfig_compiler_automoc.s"
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdecore/kconfig_compiler && g++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdecore/kconfig_compiler/kconfig_compiler_automoc.cpp -o CMakeFiles/kconfig_compiler.dir/kconfig_compiler_automoc.s

kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/kconfig_compiler_automoc.o.requires:
.PHONY : kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/kconfig_compiler_automoc.o.requires

kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/kconfig_compiler_automoc.o.provides: kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/kconfig_compiler_automoc.o.requires
	$(MAKE) -f kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/build.make kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/kconfig_compiler_automoc.o.provides.build
.PHONY : kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/kconfig_compiler_automoc.o.provides

kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/kconfig_compiler_automoc.o.provides.build: kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/kconfig_compiler_automoc.o

kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/kconfig_compiler.o: kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/flags.make
kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/kconfig_compiler.o: ../kdecore/kconfig_compiler/kconfig_compiler.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/CMakeFiles $(CMAKE_PROGRESS_2)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/kconfig_compiler.o"
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdecore/kconfig_compiler && g++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/kconfig_compiler.dir/kconfig_compiler.o -c /home/yeek/kdedev/output/build/kdelibs-v4.7.1/kdecore/kconfig_compiler/kconfig_compiler.cpp

kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/kconfig_compiler.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/kconfig_compiler.dir/kconfig_compiler.i"
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdecore/kconfig_compiler && g++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/yeek/kdedev/output/build/kdelibs-v4.7.1/kdecore/kconfig_compiler/kconfig_compiler.cpp > CMakeFiles/kconfig_compiler.dir/kconfig_compiler.i

kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/kconfig_compiler.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/kconfig_compiler.dir/kconfig_compiler.s"
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdecore/kconfig_compiler && g++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/yeek/kdedev/output/build/kdelibs-v4.7.1/kdecore/kconfig_compiler/kconfig_compiler.cpp -o CMakeFiles/kconfig_compiler.dir/kconfig_compiler.s

kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/kconfig_compiler.o.requires:
.PHONY : kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/kconfig_compiler.o.requires

kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/kconfig_compiler.o.provides: kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/kconfig_compiler.o.requires
	$(MAKE) -f kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/build.make kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/kconfig_compiler.o.provides.build
.PHONY : kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/kconfig_compiler.o.provides

kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/kconfig_compiler.o.provides.build: kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/kconfig_compiler.o

# Object files for target kconfig_compiler
kconfig_compiler_OBJECTS = \
"CMakeFiles/kconfig_compiler.dir/kconfig_compiler_automoc.o" \
"CMakeFiles/kconfig_compiler.dir/kconfig_compiler.o"

# External object files for target kconfig_compiler
kconfig_compiler_EXTERNAL_OBJECTS =

bin/kconfig_compiler: kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/kconfig_compiler_automoc.o
bin/kconfig_compiler: kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/kconfig_compiler.o
bin/kconfig_compiler: /home/yeek/kdedev/output/host/usr/arm-unknown-linux-gnueabi/sysroot/usr/lib/libQtCore.so
bin/kconfig_compiler: /home/yeek/kdedev/output/host/usr/arm-unknown-linux-gnueabi/sysroot/usr/lib/libQtXml.so
bin/kconfig_compiler: kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/build.make
bin/kconfig_compiler: kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --red --bold "Linking CXX executable ../../bin/kconfig_compiler"
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdecore/kconfig_compiler && $(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/kconfig_compiler.dir/link.txt --verbose=$(VERBOSE)
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdecore/kconfig_compiler && /home/yeek/kdedev/output/host/usr/bin/cmake -D_filename=/home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/bin/kconfig_compiler.shell -D_library_path_variable=LD_LIBRARY_PATH -D_ld_library_path="/home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/lib/./:/usr/lib:/home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/lib/.:/home/yeek/kdedev/output/host/usr/arm-unknown-linux-gnueabi/sysroot/usr/lib" -D_executable=/home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/bin/kconfig_compiler -P /home/yeek/kdedev/output/build/kdelibs-v4.7.1/cmake/modules/kde4_exec_via_sh.cmake

# Rule to build all files generated by this target.
kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/build: bin/kconfig_compiler
.PHONY : kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/build

kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/requires: kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/kconfig_compiler_automoc.o.requires
kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/requires: kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/kconfig_compiler.o.requires
.PHONY : kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/requires

kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/clean:
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdecore/kconfig_compiler && $(CMAKE_COMMAND) -P CMakeFiles/kconfig_compiler.dir/cmake_clean.cmake
.PHONY : kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/clean

kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/depend:
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/yeek/kdedev/output/build/kdelibs-v4.7.1 /home/yeek/kdedev/output/build/kdelibs-v4.7.1/kdecore/kconfig_compiler /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdecore/kconfig_compiler /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : kdecore/kconfig_compiler/CMakeFiles/kconfig_compiler.dir/depend

