# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/yeek/kdedev/output/host/usr/bin/cmake

# The command to remove a file.
RM = /home/yeek/kdedev/output/host/usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /home/yeek/kdedev/output/host/usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yeek/kdedev/output/build/kdelibs-v4.7.1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build

# Include any dependencies generated for this target.
include kdewidgets/CMakeFiles/makekdewidgets.dir/depend.make

# Include the progress variables for this target.
include kdewidgets/CMakeFiles/makekdewidgets.dir/progress.make

# Include the compile flags for this target's objects.
include kdewidgets/CMakeFiles/makekdewidgets.dir/flags.make

kdewidgets/CMakeFiles/makekdewidgets.dir/makekdewidgets_automoc.o: kdewidgets/CMakeFiles/makekdewidgets.dir/flags.make
kdewidgets/CMakeFiles/makekdewidgets.dir/makekdewidgets_automoc.o: kdewidgets/makekdewidgets_automoc.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/CMakeFiles $(CMAKE_PROGRESS_1)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object kdewidgets/CMakeFiles/makekdewidgets.dir/makekdewidgets_automoc.o"
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdewidgets && g++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/makekdewidgets.dir/makekdewidgets_automoc.o -c /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdewidgets/makekdewidgets_automoc.cpp

kdewidgets/CMakeFiles/makekdewidgets.dir/makekdewidgets_automoc.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/makekdewidgets.dir/makekdewidgets_automoc.i"
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdewidgets && g++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdewidgets/makekdewidgets_automoc.cpp > CMakeFiles/makekdewidgets.dir/makekdewidgets_automoc.i

kdewidgets/CMakeFiles/makekdewidgets.dir/makekdewidgets_automoc.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/makekdewidgets.dir/makekdewidgets_automoc.s"
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdewidgets && g++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdewidgets/makekdewidgets_automoc.cpp -o CMakeFiles/makekdewidgets.dir/makekdewidgets_automoc.s

kdewidgets/CMakeFiles/makekdewidgets.dir/makekdewidgets_automoc.o.requires:
.PHONY : kdewidgets/CMakeFiles/makekdewidgets.dir/makekdewidgets_automoc.o.requires

kdewidgets/CMakeFiles/makekdewidgets.dir/makekdewidgets_automoc.o.provides: kdewidgets/CMakeFiles/makekdewidgets.dir/makekdewidgets_automoc.o.requires
	$(MAKE) -f kdewidgets/CMakeFiles/makekdewidgets.dir/build.make kdewidgets/CMakeFiles/makekdewidgets.dir/makekdewidgets_automoc.o.provides.build
.PHONY : kdewidgets/CMakeFiles/makekdewidgets.dir/makekdewidgets_automoc.o.provides

kdewidgets/CMakeFiles/makekdewidgets.dir/makekdewidgets_automoc.o.provides.build: kdewidgets/CMakeFiles/makekdewidgets.dir/makekdewidgets_automoc.o

kdewidgets/CMakeFiles/makekdewidgets.dir/makekdewidgets.o: kdewidgets/CMakeFiles/makekdewidgets.dir/flags.make
kdewidgets/CMakeFiles/makekdewidgets.dir/makekdewidgets.o: ../kdewidgets/makekdewidgets.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/CMakeFiles $(CMAKE_PROGRESS_2)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object kdewidgets/CMakeFiles/makekdewidgets.dir/makekdewidgets.o"
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdewidgets && g++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/makekdewidgets.dir/makekdewidgets.o -c /home/yeek/kdedev/output/build/kdelibs-v4.7.1/kdewidgets/makekdewidgets.cpp

kdewidgets/CMakeFiles/makekdewidgets.dir/makekdewidgets.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/makekdewidgets.dir/makekdewidgets.i"
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdewidgets && g++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/yeek/kdedev/output/build/kdelibs-v4.7.1/kdewidgets/makekdewidgets.cpp > CMakeFiles/makekdewidgets.dir/makekdewidgets.i

kdewidgets/CMakeFiles/makekdewidgets.dir/makekdewidgets.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/makekdewidgets.dir/makekdewidgets.s"
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdewidgets && g++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/yeek/kdedev/output/build/kdelibs-v4.7.1/kdewidgets/makekdewidgets.cpp -o CMakeFiles/makekdewidgets.dir/makekdewidgets.s

kdewidgets/CMakeFiles/makekdewidgets.dir/makekdewidgets.o.requires:
.PHONY : kdewidgets/CMakeFiles/makekdewidgets.dir/makekdewidgets.o.requires

kdewidgets/CMakeFiles/makekdewidgets.dir/makekdewidgets.o.provides: kdewidgets/CMakeFiles/makekdewidgets.dir/makekdewidgets.o.requires
	$(MAKE) -f kdewidgets/CMakeFiles/makekdewidgets.dir/build.make kdewidgets/CMakeFiles/makekdewidgets.dir/makekdewidgets.o.provides.build
.PHONY : kdewidgets/CMakeFiles/makekdewidgets.dir/makekdewidgets.o.provides

kdewidgets/CMakeFiles/makekdewidgets.dir/makekdewidgets.o.provides.build: kdewidgets/CMakeFiles/makekdewidgets.dir/makekdewidgets.o

# Object files for target makekdewidgets
makekdewidgets_OBJECTS = \
"CMakeFiles/makekdewidgets.dir/makekdewidgets_automoc.o" \
"CMakeFiles/makekdewidgets.dir/makekdewidgets.o"

# External object files for target makekdewidgets
makekdewidgets_EXTERNAL_OBJECTS =

bin/makekdewidgets: kdewidgets/CMakeFiles/makekdewidgets.dir/makekdewidgets_automoc.o
bin/makekdewidgets: kdewidgets/CMakeFiles/makekdewidgets.dir/makekdewidgets.o
bin/makekdewidgets: hlib/libkdecore.so.5.6.0
bin/makekdewidgets: /home/yeek/kdedev/output/host/usr/arm-unknown-linux-gnueabi/sysroot/usr/lib/libQtDBus.so
bin/makekdewidgets: /home/yeek/kdedev/output/host/usr/arm-unknown-linux-gnueabi/sysroot/usr/lib/libQtCore.so
bin/makekdewidgets: kdewidgets/CMakeFiles/makekdewidgets.dir/build.make
bin/makekdewidgets: kdewidgets/CMakeFiles/makekdewidgets.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --red --bold "Linking CXX executable ../bin/makekdewidgets"
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdewidgets && $(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/makekdewidgets.dir/link.txt --verbose=$(VERBOSE)
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdewidgets && /home/yeek/kdedev/output/host/usr/bin/cmake -D_filename=/home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/bin/makekdewidgets.shell -D_library_path_variable=LD_LIBRARY_PATH -D_ld_library_path="/home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/lib/./:/usr/lib:/home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/lib/.:/home/yeek/kdedev/output/host/usr/arm-unknown-linux-gnueabi/sysroot/usr/lib" -D_executable=/home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/bin/makekdewidgets -P /home/yeek/kdedev/output/build/kdelibs-v4.7.1/cmake/modules/kde4_exec_via_sh.cmake

# Rule to build all files generated by this target.
kdewidgets/CMakeFiles/makekdewidgets.dir/build: bin/makekdewidgets
.PHONY : kdewidgets/CMakeFiles/makekdewidgets.dir/build

kdewidgets/CMakeFiles/makekdewidgets.dir/requires: kdewidgets/CMakeFiles/makekdewidgets.dir/makekdewidgets_automoc.o.requires
kdewidgets/CMakeFiles/makekdewidgets.dir/requires: kdewidgets/CMakeFiles/makekdewidgets.dir/makekdewidgets.o.requires
.PHONY : kdewidgets/CMakeFiles/makekdewidgets.dir/requires

kdewidgets/CMakeFiles/makekdewidgets.dir/clean:
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdewidgets && $(CMAKE_COMMAND) -P CMakeFiles/makekdewidgets.dir/cmake_clean.cmake
.PHONY : kdewidgets/CMakeFiles/makekdewidgets.dir/clean

kdewidgets/CMakeFiles/makekdewidgets.dir/depend:
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/yeek/kdedev/output/build/kdelibs-v4.7.1 /home/yeek/kdedev/output/build/kdelibs-v4.7.1/kdewidgets /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdewidgets /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdewidgets/CMakeFiles/makekdewidgets.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : kdewidgets/CMakeFiles/makekdewidgets.dir/depend

