# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/yeek/kdedev/output/host/usr/bin/cmake

# The command to remove a file.
RM = /home/yeek/kdedev/output/host/usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /home/yeek/kdedev/output/host/usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yeek/kdedev/output/build/kdelibs-v4.7.1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build

# Include any dependencies generated for this target.
include kdoctools/CMakeFiles/meinproc4.dir/depend.make

# Include the progress variables for this target.
include kdoctools/CMakeFiles/meinproc4.dir/progress.make

# Include the compile flags for this target's objects.
include kdoctools/CMakeFiles/meinproc4.dir/flags.make

kdoctools/CMakeFiles/meinproc4.dir/meinproc4_automoc.o: kdoctools/CMakeFiles/meinproc4.dir/flags.make
kdoctools/CMakeFiles/meinproc4.dir/meinproc4_automoc.o: kdoctools/meinproc4_automoc.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/CMakeFiles $(CMAKE_PROGRESS_1)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object kdoctools/CMakeFiles/meinproc4.dir/meinproc4_automoc.o"
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdoctools && g++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/meinproc4.dir/meinproc4_automoc.o -c /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdoctools/meinproc4_automoc.cpp

kdoctools/CMakeFiles/meinproc4.dir/meinproc4_automoc.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/meinproc4.dir/meinproc4_automoc.i"
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdoctools && g++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdoctools/meinproc4_automoc.cpp > CMakeFiles/meinproc4.dir/meinproc4_automoc.i

kdoctools/CMakeFiles/meinproc4.dir/meinproc4_automoc.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/meinproc4.dir/meinproc4_automoc.s"
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdoctools && g++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdoctools/meinproc4_automoc.cpp -o CMakeFiles/meinproc4.dir/meinproc4_automoc.s

kdoctools/CMakeFiles/meinproc4.dir/meinproc4_automoc.o.requires:
.PHONY : kdoctools/CMakeFiles/meinproc4.dir/meinproc4_automoc.o.requires

kdoctools/CMakeFiles/meinproc4.dir/meinproc4_automoc.o.provides: kdoctools/CMakeFiles/meinproc4.dir/meinproc4_automoc.o.requires
	$(MAKE) -f kdoctools/CMakeFiles/meinproc4.dir/build.make kdoctools/CMakeFiles/meinproc4.dir/meinproc4_automoc.o.provides.build
.PHONY : kdoctools/CMakeFiles/meinproc4.dir/meinproc4_automoc.o.provides

kdoctools/CMakeFiles/meinproc4.dir/meinproc4_automoc.o.provides.build: kdoctools/CMakeFiles/meinproc4.dir/meinproc4_automoc.o

kdoctools/CMakeFiles/meinproc4.dir/meinproc.o: kdoctools/CMakeFiles/meinproc4.dir/flags.make
kdoctools/CMakeFiles/meinproc4.dir/meinproc.o: ../kdoctools/meinproc.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/CMakeFiles $(CMAKE_PROGRESS_2)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object kdoctools/CMakeFiles/meinproc4.dir/meinproc.o"
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdoctools && g++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/meinproc4.dir/meinproc.o -c /home/yeek/kdedev/output/build/kdelibs-v4.7.1/kdoctools/meinproc.cpp

kdoctools/CMakeFiles/meinproc4.dir/meinproc.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/meinproc4.dir/meinproc.i"
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdoctools && g++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/yeek/kdedev/output/build/kdelibs-v4.7.1/kdoctools/meinproc.cpp > CMakeFiles/meinproc4.dir/meinproc.i

kdoctools/CMakeFiles/meinproc4.dir/meinproc.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/meinproc4.dir/meinproc.s"
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdoctools && g++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/yeek/kdedev/output/build/kdelibs-v4.7.1/kdoctools/meinproc.cpp -o CMakeFiles/meinproc4.dir/meinproc.s

kdoctools/CMakeFiles/meinproc4.dir/meinproc.o.requires:
.PHONY : kdoctools/CMakeFiles/meinproc4.dir/meinproc.o.requires

kdoctools/CMakeFiles/meinproc4.dir/meinproc.o.provides: kdoctools/CMakeFiles/meinproc4.dir/meinproc.o.requires
	$(MAKE) -f kdoctools/CMakeFiles/meinproc4.dir/build.make kdoctools/CMakeFiles/meinproc4.dir/meinproc.o.provides.build
.PHONY : kdoctools/CMakeFiles/meinproc4.dir/meinproc.o.provides

kdoctools/CMakeFiles/meinproc4.dir/meinproc.o.provides.build: kdoctools/CMakeFiles/meinproc4.dir/meinproc.o

kdoctools/CMakeFiles/meinproc4.dir/meinproc_common.o: kdoctools/CMakeFiles/meinproc4.dir/flags.make
kdoctools/CMakeFiles/meinproc4.dir/meinproc_common.o: ../kdoctools/meinproc_common.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/CMakeFiles $(CMAKE_PROGRESS_3)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object kdoctools/CMakeFiles/meinproc4.dir/meinproc_common.o"
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdoctools && g++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/meinproc4.dir/meinproc_common.o -c /home/yeek/kdedev/output/build/kdelibs-v4.7.1/kdoctools/meinproc_common.cpp

kdoctools/CMakeFiles/meinproc4.dir/meinproc_common.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/meinproc4.dir/meinproc_common.i"
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdoctools && g++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/yeek/kdedev/output/build/kdelibs-v4.7.1/kdoctools/meinproc_common.cpp > CMakeFiles/meinproc4.dir/meinproc_common.i

kdoctools/CMakeFiles/meinproc4.dir/meinproc_common.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/meinproc4.dir/meinproc_common.s"
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdoctools && g++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/yeek/kdedev/output/build/kdelibs-v4.7.1/kdoctools/meinproc_common.cpp -o CMakeFiles/meinproc4.dir/meinproc_common.s

kdoctools/CMakeFiles/meinproc4.dir/meinproc_common.o.requires:
.PHONY : kdoctools/CMakeFiles/meinproc4.dir/meinproc_common.o.requires

kdoctools/CMakeFiles/meinproc4.dir/meinproc_common.o.provides: kdoctools/CMakeFiles/meinproc4.dir/meinproc_common.o.requires
	$(MAKE) -f kdoctools/CMakeFiles/meinproc4.dir/build.make kdoctools/CMakeFiles/meinproc4.dir/meinproc_common.o.provides.build
.PHONY : kdoctools/CMakeFiles/meinproc4.dir/meinproc_common.o.provides

kdoctools/CMakeFiles/meinproc4.dir/meinproc_common.o.provides.build: kdoctools/CMakeFiles/meinproc4.dir/meinproc_common.o

kdoctools/CMakeFiles/meinproc4.dir/xslt.o: kdoctools/CMakeFiles/meinproc4.dir/flags.make
kdoctools/CMakeFiles/meinproc4.dir/xslt.o: ../kdoctools/xslt.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/CMakeFiles $(CMAKE_PROGRESS_4)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object kdoctools/CMakeFiles/meinproc4.dir/xslt.o"
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdoctools && g++   $(CXX_DEFINES) $(CXX_FLAGS) -DSIMPLE_XSLT -o CMakeFiles/meinproc4.dir/xslt.o -c /home/yeek/kdedev/output/build/kdelibs-v4.7.1/kdoctools/xslt.cpp

kdoctools/CMakeFiles/meinproc4.dir/xslt.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/meinproc4.dir/xslt.i"
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdoctools && g++  $(CXX_DEFINES) $(CXX_FLAGS) -DSIMPLE_XSLT -E /home/yeek/kdedev/output/build/kdelibs-v4.7.1/kdoctools/xslt.cpp > CMakeFiles/meinproc4.dir/xslt.i

kdoctools/CMakeFiles/meinproc4.dir/xslt.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/meinproc4.dir/xslt.s"
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdoctools && g++  $(CXX_DEFINES) $(CXX_FLAGS) -DSIMPLE_XSLT -S /home/yeek/kdedev/output/build/kdelibs-v4.7.1/kdoctools/xslt.cpp -o CMakeFiles/meinproc4.dir/xslt.s

kdoctools/CMakeFiles/meinproc4.dir/xslt.o.requires:
.PHONY : kdoctools/CMakeFiles/meinproc4.dir/xslt.o.requires

kdoctools/CMakeFiles/meinproc4.dir/xslt.o.provides: kdoctools/CMakeFiles/meinproc4.dir/xslt.o.requires
	$(MAKE) -f kdoctools/CMakeFiles/meinproc4.dir/build.make kdoctools/CMakeFiles/meinproc4.dir/xslt.o.provides.build
.PHONY : kdoctools/CMakeFiles/meinproc4.dir/xslt.o.provides

kdoctools/CMakeFiles/meinproc4.dir/xslt.o.provides.build: kdoctools/CMakeFiles/meinproc4.dir/xslt.o

kdoctools/CMakeFiles/meinproc4.dir/xslt_kde.o: kdoctools/CMakeFiles/meinproc4.dir/flags.make
kdoctools/CMakeFiles/meinproc4.dir/xslt_kde.o: ../kdoctools/xslt_kde.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/CMakeFiles $(CMAKE_PROGRESS_5)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object kdoctools/CMakeFiles/meinproc4.dir/xslt_kde.o"
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdoctools && g++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/meinproc4.dir/xslt_kde.o -c /home/yeek/kdedev/output/build/kdelibs-v4.7.1/kdoctools/xslt_kde.cpp

kdoctools/CMakeFiles/meinproc4.dir/xslt_kde.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/meinproc4.dir/xslt_kde.i"
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdoctools && g++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/yeek/kdedev/output/build/kdelibs-v4.7.1/kdoctools/xslt_kde.cpp > CMakeFiles/meinproc4.dir/xslt_kde.i

kdoctools/CMakeFiles/meinproc4.dir/xslt_kde.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/meinproc4.dir/xslt_kde.s"
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdoctools && g++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/yeek/kdedev/output/build/kdelibs-v4.7.1/kdoctools/xslt_kde.cpp -o CMakeFiles/meinproc4.dir/xslt_kde.s

kdoctools/CMakeFiles/meinproc4.dir/xslt_kde.o.requires:
.PHONY : kdoctools/CMakeFiles/meinproc4.dir/xslt_kde.o.requires

kdoctools/CMakeFiles/meinproc4.dir/xslt_kde.o.provides: kdoctools/CMakeFiles/meinproc4.dir/xslt_kde.o.requires
	$(MAKE) -f kdoctools/CMakeFiles/meinproc4.dir/build.make kdoctools/CMakeFiles/meinproc4.dir/xslt_kde.o.provides.build
.PHONY : kdoctools/CMakeFiles/meinproc4.dir/xslt_kde.o.provides

kdoctools/CMakeFiles/meinproc4.dir/xslt_kde.o.provides.build: kdoctools/CMakeFiles/meinproc4.dir/xslt_kde.o

# Object files for target meinproc4
meinproc4_OBJECTS = \
"CMakeFiles/meinproc4.dir/meinproc4_automoc.o" \
"CMakeFiles/meinproc4.dir/meinproc.o" \
"CMakeFiles/meinproc4.dir/meinproc_common.o" \
"CMakeFiles/meinproc4.dir/xslt.o" \
"CMakeFiles/meinproc4.dir/xslt_kde.o"

# External object files for target meinproc4
meinproc4_EXTERNAL_OBJECTS =

bin/meinproc4: kdoctools/CMakeFiles/meinproc4.dir/meinproc4_automoc.o
bin/meinproc4: kdoctools/CMakeFiles/meinproc4.dir/meinproc.o
bin/meinproc4: kdoctools/CMakeFiles/meinproc4.dir/meinproc_common.o
bin/meinproc4: kdoctools/CMakeFiles/meinproc4.dir/xslt.o
bin/meinproc4: kdoctools/CMakeFiles/meinproc4.dir/xslt_kde.o
bin/meinproc4: hlib/libkdecore.so.5.6.0
bin/meinproc4: /home/yeek/kdedev/output/host/usr/arm-unknown-linux-gnueabi/sysroot/usr/lib/libxml2.so
bin/meinproc4: /home/yeek/kdedev/output/host/usr/arm-unknown-linux-gnueabi/sysroot/usr/lib/libxslt.so
bin/meinproc4: /home/yeek/kdedev/output/host/usr/arm-unknown-linux-gnueabi/sysroot/usr/lib/libexslt.so
bin/meinproc4: /home/yeek/kdedev/output/host/usr/arm-unknown-linux-gnueabi/sysroot/usr/lib/libQtDBus.so
bin/meinproc4: /home/yeek/kdedev/output/host/usr/arm-unknown-linux-gnueabi/sysroot/usr/lib/libQtCore.so
bin/meinproc4: kdoctools/CMakeFiles/meinproc4.dir/build.make
bin/meinproc4: kdoctools/CMakeFiles/meinproc4.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --red --bold "Linking CXX executable ../bin/meinproc4"
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdoctools && $(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/meinproc4.dir/link.txt --verbose=$(VERBOSE)
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdoctools && /home/yeek/kdedev/output/host/usr/bin/cmake -D_filename=/home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/bin/meinproc4.shell -D_library_path_variable=LD_LIBRARY_PATH -D_ld_library_path="/home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/lib/./:/usr/lib:/home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/lib/.:/home/yeek/kdedev/output/host/usr/arm-unknown-linux-gnueabi/sysroot/usr/lib" -D_executable=/home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/bin/meinproc4 -P /home/yeek/kdedev/output/build/kdelibs-v4.7.1/cmake/modules/kde4_exec_via_sh.cmake

# Rule to build all files generated by this target.
kdoctools/CMakeFiles/meinproc4.dir/build: bin/meinproc4
.PHONY : kdoctools/CMakeFiles/meinproc4.dir/build

kdoctools/CMakeFiles/meinproc4.dir/requires: kdoctools/CMakeFiles/meinproc4.dir/meinproc4_automoc.o.requires
kdoctools/CMakeFiles/meinproc4.dir/requires: kdoctools/CMakeFiles/meinproc4.dir/meinproc.o.requires
kdoctools/CMakeFiles/meinproc4.dir/requires: kdoctools/CMakeFiles/meinproc4.dir/meinproc_common.o.requires
kdoctools/CMakeFiles/meinproc4.dir/requires: kdoctools/CMakeFiles/meinproc4.dir/xslt.o.requires
kdoctools/CMakeFiles/meinproc4.dir/requires: kdoctools/CMakeFiles/meinproc4.dir/xslt_kde.o.requires
.PHONY : kdoctools/CMakeFiles/meinproc4.dir/requires

kdoctools/CMakeFiles/meinproc4.dir/clean:
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdoctools && $(CMAKE_COMMAND) -P CMakeFiles/meinproc4.dir/cmake_clean.cmake
.PHONY : kdoctools/CMakeFiles/meinproc4.dir/clean

kdoctools/CMakeFiles/meinproc4.dir/depend:
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/yeek/kdedev/output/build/kdelibs-v4.7.1 /home/yeek/kdedev/output/build/kdelibs-v4.7.1/kdoctools /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdoctools /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdoctools/CMakeFiles/meinproc4.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : kdoctools/CMakeFiles/meinproc4.dir/depend

