# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/yeek/kdedev/output/host/usr/bin/cmake

# The command to remove a file.
RM = /home/yeek/kdedev/output/host/usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /home/yeek/kdedev/output/host/usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yeek/kdedev/output/build/kdelibs-v4.7.1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build

# Include any dependencies generated for this target.
include kdoctools/CMakeFiles/docbookl10nhelper.dir/depend.make

# Include the progress variables for this target.
include kdoctools/CMakeFiles/docbookl10nhelper.dir/progress.make

# Include the compile flags for this target's objects.
include kdoctools/CMakeFiles/docbookl10nhelper.dir/flags.make

kdoctools/CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper_automoc.o: kdoctools/CMakeFiles/docbookl10nhelper.dir/flags.make
kdoctools/CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper_automoc.o: kdoctools/docbookl10nhelper_automoc.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/CMakeFiles $(CMAKE_PROGRESS_1)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object kdoctools/CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper_automoc.o"
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdoctools && g++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper_automoc.o -c /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdoctools/docbookl10nhelper_automoc.cpp

kdoctools/CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper_automoc.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper_automoc.i"
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdoctools && g++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdoctools/docbookl10nhelper_automoc.cpp > CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper_automoc.i

kdoctools/CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper_automoc.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper_automoc.s"
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdoctools && g++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdoctools/docbookl10nhelper_automoc.cpp -o CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper_automoc.s

kdoctools/CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper_automoc.o.requires:
.PHONY : kdoctools/CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper_automoc.o.requires

kdoctools/CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper_automoc.o.provides: kdoctools/CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper_automoc.o.requires
	$(MAKE) -f kdoctools/CMakeFiles/docbookl10nhelper.dir/build.make kdoctools/CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper_automoc.o.provides.build
.PHONY : kdoctools/CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper_automoc.o.provides

kdoctools/CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper_automoc.o.provides.build: kdoctools/CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper_automoc.o

kdoctools/CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper.o: kdoctools/CMakeFiles/docbookl10nhelper.dir/flags.make
kdoctools/CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper.o: ../kdoctools/docbookl10nhelper.cpp
	$(CMAKE_COMMAND) -E cmake_progress_report /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/CMakeFiles $(CMAKE_PROGRESS_2)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object kdoctools/CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper.o"
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdoctools && g++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper.o -c /home/yeek/kdedev/output/build/kdelibs-v4.7.1/kdoctools/docbookl10nhelper.cpp

kdoctools/CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper.i"
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdoctools && g++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/yeek/kdedev/output/build/kdelibs-v4.7.1/kdoctools/docbookl10nhelper.cpp > CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper.i

kdoctools/CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper.s"
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdoctools && g++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/yeek/kdedev/output/build/kdelibs-v4.7.1/kdoctools/docbookl10nhelper.cpp -o CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper.s

kdoctools/CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper.o.requires:
.PHONY : kdoctools/CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper.o.requires

kdoctools/CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper.o.provides: kdoctools/CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper.o.requires
	$(MAKE) -f kdoctools/CMakeFiles/docbookl10nhelper.dir/build.make kdoctools/CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper.o.provides.build
.PHONY : kdoctools/CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper.o.provides

kdoctools/CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper.o.provides.build: kdoctools/CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper.o

# Object files for target docbookl10nhelper
docbookl10nhelper_OBJECTS = \
"CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper_automoc.o" \
"CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper.o"

# External object files for target docbookl10nhelper
docbookl10nhelper_EXTERNAL_OBJECTS =

bin/docbookl10nhelper: kdoctools/CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper_automoc.o
bin/docbookl10nhelper: kdoctools/CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper.o
bin/docbookl10nhelper: /home/yeek/kdedev/output/host/usr/arm-unknown-linux-gnueabi/sysroot/usr/lib/libQtCore.so
bin/docbookl10nhelper: kdoctools/CMakeFiles/docbookl10nhelper.dir/build.make
bin/docbookl10nhelper: kdoctools/CMakeFiles/docbookl10nhelper.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --red --bold "Linking CXX executable ../bin/docbookl10nhelper"
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdoctools && $(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/docbookl10nhelper.dir/link.txt --verbose=$(VERBOSE)
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdoctools && /home/yeek/kdedev/output/host/usr/bin/cmake -D_filename=/home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/bin/docbookl10nhelper.shell -D_library_path_variable=LD_LIBRARY_PATH -D_ld_library_path="/home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/lib/./:/usr/lib:/home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/lib/.:/home/yeek/kdedev/output/host/usr/arm-unknown-linux-gnueabi/sysroot/usr/lib" -D_executable=/home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/bin/docbookl10nhelper -P /home/yeek/kdedev/output/build/kdelibs-v4.7.1/cmake/modules/kde4_exec_via_sh.cmake
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdoctools && ../bin/docbookl10nhelper /home/yeek/kdedev/output/host/usr/arm-unknown-linux-gnueabi/sysroot/usr/share/xsl/docbook /home/yeek/kdedev/output/build/kdelibs-v4.7.1/kdoctools/customization/xsl /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdoctools/customization/xsl

# Rule to build all files generated by this target.
kdoctools/CMakeFiles/docbookl10nhelper.dir/build: bin/docbookl10nhelper
.PHONY : kdoctools/CMakeFiles/docbookl10nhelper.dir/build

kdoctools/CMakeFiles/docbookl10nhelper.dir/requires: kdoctools/CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper_automoc.o.requires
kdoctools/CMakeFiles/docbookl10nhelper.dir/requires: kdoctools/CMakeFiles/docbookl10nhelper.dir/docbookl10nhelper.o.requires
.PHONY : kdoctools/CMakeFiles/docbookl10nhelper.dir/requires

kdoctools/CMakeFiles/docbookl10nhelper.dir/clean:
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdoctools && $(CMAKE_COMMAND) -P CMakeFiles/docbookl10nhelper.dir/cmake_clean.cmake
.PHONY : kdoctools/CMakeFiles/docbookl10nhelper.dir/clean

kdoctools/CMakeFiles/docbookl10nhelper.dir/depend:
	cd /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/yeek/kdedev/output/build/kdelibs-v4.7.1 /home/yeek/kdedev/output/build/kdelibs-v4.7.1/kdoctools /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdoctools /home/yeek/kdedev/output/build/kdelibs-v4.7.1/build/kdoctools/CMakeFiles/docbookl10nhelper.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : kdoctools/CMakeFiles/docbookl10nhelper.dir/depend

